# Session 12: NumPy introduction & 1D Array & 2D Array
	Objectives: Understanding the first data science library
	Outcome of the Class: Introduction to the numpy array and how to create numpy array using list.

**NumPy = library in python programming**
1. stands for numerical python
2. it is faster than list
3. we can perform mathematical calculations
4. use NumPy to implement the concept of array
**List**
1. is not suitable for bigger dataset
2. can't perform any mathematical operations
**Array**
1. a data structure
2. used to store multiple values
3. can store only one type of value at a time
4. faster than a list
5. can perform calculation over array
**How to create NumPy array**
1. from list
2. from tuple

In [ ]:
# importing the library of numpy
import numpy as np
# creating the numpy array using list
list1 = [30, 90, 87, 45, 67]
print(list1)
print(type(list1))
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

[30, 90, 87, 45, 67]
<class 'list'>
[30 90 87 45 67]
<class 'numpy.ndarray'>


**1D array(vector): [90, 60, 30, 80]**

In [ ]:
# second approach to create the numpy array
arr2 = np.array([50, 90, 80, 87, 54])
print(arr2)
print(type(arr2))

[50 90 80 87 54]
<class 'numpy.ndarray'>


**2D array(matrix): to create 2D array, we need multiple list**

**2D array: arr2 = np.array([[1, 2, 3],[4, 5, 6], [6, 7, 8]])**

**list of list: neasted list [[1, 2, 3], [4, 5, 6]]**


In [ ]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr3)
print(type(arr3)) # type
print(arr3.ndim) # dimension of array
print(arr3.size) # size of array
print(arr3.shape) # shape of array (how many row, how many column)
print(arr3.dtype) # type of value present in the array

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
2
6
(3, 2)
int64


# Session 13: NumPy: np.zeros() & np.ones() & Matrix multiplication
	Outcome of the Class: Implementation of Numpy array and introduction to dot product/matrix multiplication

In [ ]:
import numpy as np
arr5 = np.array([500, 1000, "Govind", "Python Programming"])
print(arr5)
print(arr5.dtype)

['500' '1000' 'Govind' 'Python Programming']
<U21


In [ ]:
# np.zeros() = used to convert all the elements into 0
arr6 = np.zeros((4, 5))
print(arr6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr7 = np.zeros ((5, 5), dtype = 'int')
print(arr7)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
arr8 = np.zeros((5, 5), dtype='str')
print(arr8)
print(arr8.dtype)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
<U1


In [ ]:
# np.ones() = used to convert all the elements into 1
arr9 = np.ones((5, 7))
print(arr9)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
arr10 = np.ones((5, 7), dtype = 'int')
print(arr10)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


**Matrix Multiplication**

In [ ]:
arr1 = np.array([[2, 4],[5, 6]])
arr2 = np.array([[3, 1], [4, 7]])
print(arr1)
print()
print(arr2)

[[2 4]
 [5 6]]

[[3 1]
 [4 7]]


In [ ]:
# normal multiplication of two matrix = element wise multiplication
print(arr1 * arr2)

[[ 6  4]
 [20 42]]


In [ ]:
# dot product = matrix multiplication
print(arr1.dot(arr2))

[[22 30]
 [39 47]]


In [ ]:
# exampple2
arr3 = np.array([[3, 2, 5],
                 [3, 2, 1]])
arr4 = np.array([[3, 8],
                 [5, 1],
                 [7, 3]])
print(arr3.dot(arr4))

[[54 41]
 [26 29]]


In [ ]:
arr5 = np.array([[3, 2], [5, 4]])
print(arr5)
print()
arr6 = np.array([[9, 4],[8, 1],[7, 3]])
print(arr6)
print()
print(arr5.dot(arr6)) # can't multiply two arrays with different dimension

[[3 2]
 [5 4]]

[[9 4]
 [8 1]
 [7 3]]



ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

# Session 14: arange(); random: rand(), randint(); reshape()
	Objectives: Operations and functionality using NumPy
	Outcome of the Class: Implementation of numpy functionality using python


**arange() = will give the sequencial number**


In [ ]:
import numpy as np
arr1 = np.arange(10)
print(arr1)
print(type(arr1))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
arr2 = np.arange(5, 15)
print(arr2)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr3 = np.arange(10, 100, 2)
print(arr3)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [ ]:
arr4 = np.arange(10, 100, 3, dtype="float")
print(arr4)

[10. 13. 16. 19. 22. 25. 28. 31. 34. 37. 40. 43. 46. 49. 52. 55. 58. 61.
 64. 67. 70. 73. 76. 79. 82. 85. 88. 91. 94. 97.]


**Random module**

**rand() = has a fixed range. example: 0 to 1**

**randint() = range we can decide**


In [ ]:
from numpy import random
# i want a random number between 0 to 100
x = random.randint(100)
print(x)

14


In [ ]:
# I want a random number between 0 to 1
y = random.rand()
print(y)

0.045612039267095894


In [ ]:
# I want 10 random number from 0 to 1
z = random.rand(10)
print(z)

[0.17297098 0.872278   0.48876809 0.56156435 0.07382558 0.12251348
 0.09027088 0.56594997 0.6161878  0.23315678]


In [ ]:
# I want 10 random number in the range of  10 to 100
a = np.random.randint(10, 100, size = 10)
print(a)

[55 58 80 85 77 67 12 70 88 83]


In [ ]:
# I want 10 random number in the range of 100 to 500
b = np.random.randint(100, 500, size = 10)
print(b)

[488 176 322 496 230 443 284 288 346 316]


**reshape() = convert the dimension of the numpy array**

In [ ]:
arr1 = np.arange(10).reshape(2, 5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
arr2 = np.arange(10).reshape(5, 2)
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 2D
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
arr1.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# converting 1D to 3D
arr10 = np.arange(1, 19)
arr10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [ ]:
# 6 arrays with 1 rows and 3 columns
arr10.reshape(6, 1, 3)

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]],

       [[16, 17, 18]]])

In [ ]:
# 3 arrays with 3 rows and 2 columns
arr10.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
# 2 arrays with 3 rows and 3 columns
arr10.reshape(2, 3, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Session 15: Slicing in NumPy, Array
	Objectives: Implementation of Pandas functionality
	Outcome of the Class: How to handle the numpy slicing - 1D, 2D and 3D?

In [ ]:
import numpy as np
arr1 = np.array([30, 90, 98, 78, 92])
print(arr1)
print(arr1[2:4])
print(arr1[:])
print(arr1[::-1])
print(arr1[1:5:2])

[30 90 98 78 92]
[98 78]
[30 90 98 78 92]
[92 78 98 90 30]
[90 78]


**Slicing in 2D array**

In [ ]:
arr2 = np.array([[9, 4, 6], [8, 5, 3]])
print(arr2)

[[9 4 6]
 [8 5 3]]


In [ ]:
print(arr2[1:2, 1:3])

[[5 3]]


In [ ]:
arr3 = np.array([[8, 2, 8, 7], [5, 6, 8, 5], [9, 15, 8, 35]])
print(arr3)

[[ 8  2  8  7]
 [ 5  6  8  5]
 [ 9 15  8 35]]


In [ ]:
print(arr3[1:3, 1:4])

[[ 6  8  5]
 [15  8 35]]


In [ ]:
print(arr3[0:3, 1:4])

[[ 2  8  7]
 [ 6  8  5]
 [15  8 35]]


In [ ]:
print(arr3[-2:, -4:])

[[ 5  6  8  5]
 [ 9 15  8 35]]


In [ ]:
print(arr3[-3:, -2:])

[[ 8  7]
 [ 8  5]
 [ 8 35]]


In [ ]:
print(arr3[-3:, -4:-2])

[[ 8  2]
 [ 5  6]
 [ 9 15]]


In [ ]:
arr4 = np.array([[40, 60],[90, 20]])
print(arr4[1:2, 0:1])

[[90]]


**Slicing in 3D**

In [ ]:
arr4 = np.array([[[90, 20, 32], [40, 80, 32], [36, 90, 43]]])
print(arr4)

[[[90 20 32]
  [40 80 32]
  [36 90 43]]]


In [ ]:
print(arr4[0:2:2])

[[[90 20 32]
  [40 80 32]
  [36 90 43]]]


In [ ]:
print(arr4[0,1,1:3])

[80 32]


In [ ]:
print(arr4[0,2,2])

43


In [ ]:
arr4.shape

(1, 3, 3)

In [ ]:
arr6 = np.array([[[90, 20, 32], [40, 80, 32]], [[30, 90, 43], [40, 90, 98]]])
print(arr6)

[[[90 20 32]
  [40 80 32]]

 [[30 90 43]
  [40 90 98]]]


In [ ]:
arr6.shape

(2, 2, 3)

In [ ]:
print(arr6[1, 0:2, 1])

[90 90]


In [ ]:
print(arr6[1:2,0:2,1:2])

[[[90]
  [90]]]


**Sorting in Array**

In [ ]:
# original array
arr7 = np.array([[90, 908, 76], [78, 56, 73], [23, 45, 71]])
print(arr7)

[[ 90 908  76]
 [ 78  56  73]
 [ 23  45  71]]


In [ ]:
# np.sort()
print(np.sort(arr7))

[[ 76  90 908]
 [ 56  73  78]
 [ 23  45  71]]


In [ ]:
# np.sort() orizontally
print(np.sort(arr7, axis=None))

[ 23  45  56  71  73  76  78  90 908]


In [ ]:
# row wise
print(np.sort(arr7, axis=1))

[[ 76  90 908]
 [ 56  73  78]
 [ 23  45  71]]


In [ ]:
# column wise
print(np.sort(arr7, axis=0))

[[ 23  45  71]
 [ 78  56  73]
 [ 90 908  76]]
