# Introduction Numpy

## What is Numpy ?

NumPy is a Python library used for working with arrays. \
It also has functions for working in domain of linear algebra, fourier transform, and matrices. \
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.\
NumPy stands for Numerical Python.

## Why Use Numpy in python ?
In Python we have lists that serve the purpose of arrays, but they are slow to process. \
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.\
Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.\
This behavior is called locality of reference in computer science.\
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## Numpy import and use

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## Dimesnsions in Array
 1) 0 Dimensions \
 2) 1 Dimensions \
 3) 2 Dimesnions

In [ ]:
## the Program is 0D Array

import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
## The Program is 1D Array

import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
## The Program is 2D Array

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
## The proram is 3D Array

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## How to check the dimensions of Array

In [ ]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[a,b,c]]])
print("The Array Dimension: ", a.ndim)
print("The Array Dimension: ",b.ndim)
print("The Array Dimension: ",c.ndim)
print("The Array Dimension: ",d.ndim)

The Array Dimension:  0
The Array Dimension:  1
The Array Dimension:  2
The Array Dimension:  3


## Higher Dimensional Arrays

In [ ]:
import numpy as np
a = np.array([1,2,3] , ndmin=5)
print(a)
print("Numbers of Dimension in Array" , a.ndim)

[[[[[1 2 3]]]]]
Numbers of Dimension in Array 5


## Numpy Indexing Array

In [ ]:
# Acess Array First Element

import numpy as np
a = np.array([1,2,3,4,5])
print("This is First Element in Array is " , a[0])

This is First Element in Array is  1


In [ ]:
# Acess Array Second Element

import numpy as np
a = np.array([1,2,3,4,5])
print("This is Second Element in Array is " , a[1])

This is Second Element in Array is  2


In [ ]:
# Acess Array Third Element

import numpy as np
a = np.array([1,2,3,4,5])
print("This is Third Element in Array is " , a[2])

This is Third Element in Array is  3


In [ ]:
# Acess Array First Element and 3 Element and add Both

import numpy as np
a = np.array([1,2,3,4,5])
print("The Sum of Array is 'Second Element' and 'Fourth Element' is " , a[2]+a[4])

The Sum of Array is 'Second Element' and 'Fourth Element' is  8


## Acess 2D Array

In [ ]:
# Access the 2nd element on 1st dim:

import numpy as np
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [ ]:
# Access the 5th element on 2nd dim:

import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,4])

10


In [ ]:
# Access the third element of the second array of the first array:

import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(a[0,1,2])

6


# NumPy Array

## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
# Slice elements from index 1 to index 5 from the following array:

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:5])

[2 3 4 5]


In [ ]:
# Slice elements from index 4 to the end of the array:

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[4:])

[5 6 7 8 9]


In [ ]:
# Slice elements from the beginning to index 4 (not included):

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[:4])

[1 2 3 4]


## Negative Slicing
Use the minus operator to refer to an index from the end:

In [ ]:
# Slice from the index 3 from the end to index 1 from the end:

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[-3:-1])

[7 8]


## STEP
Use the step value to determine the step of the slicing:

In [ ]:
# Return every other element from index 1 to index 5:

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:6:3])

[2 5]


In [ ]:
# Return every other element from the entire array:

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[::2])

[1 3 5 7 9]


## Slicing 2-D Arrays

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])#

[7 8 9]


In [ ]:
# From both elements, return index 2:

import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]


## NumPy Data Types
By default Python have these data types:

## 1) strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
## 2) integer - used to represent integer numbers. e.g. -1, -2, -3
## 3) float - used to represent real numbers. e.g. 1.2, 42.42
## 4) boolean - used to represent True or False.

## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

### 1) i - integer
### 2) b - boolean
### 3) u - unsigned integer
### 4) f - float
### 5) c - complex float
### 6) m - timedelta
### 7) M - datetime
### 8) O - object
### 9) S - string
### 10) U - unicode string
### 11) V - fixed chunk of memory for other type ( void )


## Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [ ]:
# Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [ ]:
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print("This is 'float' Data Type :"  ,arr)
print("This is 'Integer' Data Type :" , newarr)
print(newarr.dtype)

This is 'float' Data Type : [1.1 2.1 3.1]
This is 'Integer' Data Type : [1 2 3]
int32


In [ ]:
# Change data type from float to integer by using int as parameter value:


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print("This Data Type is 'int' :" , newarr)
print(newarr.dtype)


This Data Type is 'int' : [1 2 3]
int32


In [ ]:
# Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View

## The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## COPY:

In [ ]:
# Make a copy, change the original array, and display both arrays:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print("Orginal Data copy" , x)
print("Change Data Value",arr)


Orginal Data copy [1 2 3 4 5]
Change Data Value [42  2  3  4  5]


## VIEW:

In [ ]:
# Make a view, change the original array, and display both arrays:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 40
print("View Data" , x)
print("Change Value" , arr)

View Data [40  2  3  4  5]
Change Value [40  2  3  4  5]


## Check if Array Owns it's Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
# Print the value of the base attribute to check if an array owns it's data or not:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## NumPy Array Shape

## Shape of an Array
The shape of an array is the number of elements in each dimension.

## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# Print the shape of a 2-D array:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,19]])
print(arr.shape)

#The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

(2, 5)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## NumPy Array Reshaping
Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D


In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new = arr.reshape(4,3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new = arr.reshape(2,3,2)
print(new)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Returns Copy or View?

In [ ]:
# Check if the returned array is a copy or a view:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


## Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,2,-1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
# Convert the array into a 1D array:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]


## NumPy Array Iterating
## Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
# Iterate on the elements of the following 1-D array:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# Iterate on the elements of the following 2-D array:
import numpy as np
arr = np.array([[1,2,3,4] , [5,6,7,8,]])
for x in arr:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [ ]:
# Iterate on each scalar element of the 2-D array:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


## Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [ ]:
# Iterate on the elements of the following 3-D array:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in arr:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterate down to the scalars:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
# Iterate through the following 3-D array:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
# Iterate through the array as a string:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(arr , flags = ['buffered'], op_dtypes = ['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'


## Iterating With Different Step Size
We can use filtering and followed by iteration.

In [ ]:
# Iterate through every scalar element of the 2D array skipping 1 element:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
6
8
10


## Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
# Enumerate on following 1D arrays elements:
import numpy as np
arr = np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Enumerate on following 2D array's elements:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

# Example

In [ ]:
# Join two arrays
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Join two 2-D arrays along rows (axis=1):
import numpy as np
arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[6,7],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)
arr = np.concatenate((arr1,arr2),axis=1)
arr

[[ 1  2]
 [ 4  5]
 [ 6  7]
 [ 9 10]]


array([[ 1,  2,  6,  7],
       [ 4,  5,  9, 10]])

# Joining Arrays Using Stack Functions

Stacking is same as concentation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

# Example

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows

## NumPy provides a helper function : hstack() to stack along rows.

## Example

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
### Numpy provides a helper function: vstack() to stack along columns.

# Example

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)
### NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

# Example

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

## Splitting NumPy Arrays

Splitting is reverse operation of joining.
Joining merges multiple arrays into one and splitting breaks one array into multiple.

We use array_split() for splitting arrays_split() for spliting arrays, we pass it the array we want to split and the number of splits.

# Example

In [ ]:
# Split the array in 3 parts:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Note :
The return value is an array containing three arrays.

If the array has left elements than required, it will adjust from the end accordingly.

# Example

In [ ]:
# Split the array in 4 parts:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Note:
We also have the method split() available but it will not adjust the elements when elements are less in  source array for splitting like in example above, array_split() worked properly but split() would fail.

# Split Into Arrays

The return value of the array_split() method is an array containing each of the split as an array.

If you split na array into 3 arrays, you can access them from the result just like any array element:

# Example

In [ ]:
# Access the splitted arrays:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays

Use the same syntax when splitting 2-D Arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

# Example

In [ ]:
# Split the 2-D array into three 2-D arrays.
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


The example above returns three 2-D arrays.

Let's look at another example, this time each element in the 2-D arrays contains 3 elements.

# Example

In [ ]:
# Split the 2-D array into three 2-D arrays.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis = 1).

# Example

In [ ]:
# Split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using hsplit() opposite of hstack()

# Example

In [ ]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPySearching Arrays

##  Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array,use the where() method.

# Example

In [ ]:
# Find the indexes Where the value is 4:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


The Example above will return a tuple: (array ([3,5,6]))

Which means that the value 4 is present at index 3,5,and 6.

# Example

In [ ]:
# Find the indexes where the values are even:

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


# Example

In [ ]:
# Find the indexes where the value are odd:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and return the index where the specified value would be inserted to maintain the search order.
#  
#  
The searchsorted() method is assumed to be used on sorted arrays.

# Example

In [ ]:
# Find the indexes where the value 7 should be inserted:

import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


Example explained :The number 7 should be inserted on index 1 to remain the sort order.

The Method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value..

# Search From the Right Side

By default the left most index is returned, but we can give side = "right" to return the right most index instead.

# Example

In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7,side = "right")
print(x)

2


Example explained : The number 7 should be inserted on index 2 to remain the sort order.

The method starts the search form the right and returns the first index where the number 7 is no longer less thyan the next value.

# Multiple values

To search for more than one value, use an array with the specified values.

# Example

In [ ]:
# Find the indexes where the values 2,4 and 6 shoud be installed:
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


The return value is an array: [1 2 3] containing the three  indexes where 2,4,6 would be inserted in the orginal array to maintain the order.

# NumPy Sorting Arrays

## Sorting Arrays

sorting mean putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical,ascending or descending.

The NumPy ndaaray objecy has a function called sort(),that sort a specified array.

# Example

In [ ]:
# Sort the array:
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


# Note :
This method returns a copy of the array, leaving the orginal array unchanged.

You can also sort arrays of strings, or any other data type:

# Example

In [ ]:
# sort the array alphabetically:
import numpy as np
arr = np.array(["banana","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


# Example

In [ ]:
# Sort a boolean array:
import numpy as np
arr = np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


# Sorting a 2-D Array
### IF you use the sort() method on a 2-D array, both arrays will be sorted:

# Example

In [ ]:
# Sort a 2-D array:
import numpy as np
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

### Filterings Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at the index is False that element is executed from the filtered array.

# Example

In [ ]:
# Create an array form the elements on index 0 and 2:
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)


[41 43]


The examole above will return [41 , 43], why ?

Because the new filter contains only yhe values where the filter array had the value True, in the case, index 0 and 2.

# Creating the Filter Array

In the wxample above we hard-coded the True and False values,but the common use is to create a filter array based on conditions.

# Example

In [ ]:
# Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41,42,43,44])

# Create an empty list
filter_arr = []

# Go through each element in arr
for element in arr:
# If the element is higher than 42, set the values to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


# Example

In [ ]:
#Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]
